//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChart) DeepCopyInto(out *ArmadaChart) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChart.
func (in *ArmadaChart) DeepCopy() *ArmadaChart {
	if in == nil {
		return nil
	}
	out := new(ArmadaChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChart) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartDeleteResource) DeepCopyInto(out *ArmadaChartDeleteResource) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartDeleteResource.
func (in *ArmadaChartDeleteResource) DeepCopy() *ArmadaChartDeleteResource {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartDeleteResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartList) DeepCopyInto(out *ArmadaChartList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArmadaChart, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartList.
func (in *ArmadaChartList) DeepCopy() *ArmadaChartList {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChartList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartPreUpgrade) DeepCopyInto(out *ArmadaChartPreUpgrade) {
	*out = *in
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]ArmadaChartDeleteResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartPreUpgrade.
func (in *ArmadaChartPreUpgrade) DeepCopy() *ArmadaChartPreUpgrade {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartPreUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartSource) DeepCopyInto(out *ArmadaChartSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartSource.
func (in *ArmadaChartSource) DeepCopy() *ArmadaChartSource {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartSpec) DeepCopyInto(out *ArmadaChartSpec) {
	*out = *in
	out.Source = in.Source
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.Wait.DeepCopyInto(&out.Wait)
	out.Test = in.Test
	in.Upgrade.DeepCopyInto(&out.Upgrade)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartSpec.
func (in *ArmadaChartSpec) DeepCopy() *ArmadaChartSpec {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartStatus) DeepCopyInto(out *ArmadaChartStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartStatus.
func (in *ArmadaChartStatus) DeepCopy() *ArmadaChartStatus {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartTestOptions) DeepCopyInto(out *ArmadaChartTestOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartTestOptions.
func (in *ArmadaChartTestOptions) DeepCopy() *ArmadaChartTestOptions {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartTestOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartUpgrade) DeepCopyInto(out *ArmadaChartUpgrade) {
	*out = *in
	in.PreUpgrade.DeepCopyInto(&out.PreUpgrade)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartUpgrade.
func (in *ArmadaChartUpgrade) DeepCopy() *ArmadaChartUpgrade {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartWait) DeepCopyInto(out *ArmadaChartWait) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ArmadaChartWaitResources != nil {
		in, out := &in.ArmadaChartWaitResources, &out.ArmadaChartWaitResources
		*out = make([]ArmadaChartWaitResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Native != nil {
		in, out := &in.Native, &out.Native
		*out = new(ArmadaChartWaitNative)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartWait.
func (in *ArmadaChartWait) DeepCopy() *ArmadaChartWait {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartWait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartWaitNative) DeepCopyInto(out *ArmadaChartWaitNative) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartWaitNative.
func (in *ArmadaChartWaitNative) DeepCopy() *ArmadaChartWaitNative {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartWaitNative)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartWaitResource) DeepCopyInto(out *ArmadaChartWaitResource) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartWaitResource.
func (in *ArmadaChartWaitResource) DeepCopy() *ArmadaChartWaitResource {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartWaitResource)
	in.DeepCopyInto(out)
	return out
}
